### ISSUE TITLE
Generate bookmark snippets

### ISSUE THREAD

**Issue by sroettering** [push-based/awesome-web-performance-snippets#4]
### Feature Request
Creating bookmark snippets manually is quite the pain. An automatic solution would be to generate the snippets via Github Actions.

**Comment by BioPhoton** [comment]
Hi @sroettering !

I love this idea!  ❤
So the generated script could be already minified and wrapped in an IIFE. 
In GitHub people could later on then just click the copy code button and paste the code to a bookmark!
<img width="922" alt="copy-code" src="https://user-images.githubusercontent.com/10064416/184325192-1c491656-6c9f-487d-b100-171651662287.PNG">

A really nice idea! Thanks again for pointing it out.

**Comment by BioPhoton** [comment]
hi @sroettering!

The PR #8 implements a github action for auto generating of the snippets. 

In older PR's I added a feature to bookstrap chromium with all available snippets set up as book marks
